config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # routes pour reviews dans page user
  resources :users, only: [] do
    resources :reviews, only: %i[new create]
  end

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "mymissions", to: "missions#myindex"
  get "mymissions_candidates", to: "missions#myindex_candidate"
  get "user/:id", to: "pages#user", as: :userpage

  resources :missions do
    resources :mission_candidates, only: %i[create update edit destroy]
  end
  resources :chatrooms, only: %i[create show index] do
    resources :messages, only: :create
  end
  # routes pour décliner et accepter candidats à la mission
  resources :mission_candidates, only: [] do
    member do
      patch :accepted
      patch :declined
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="apply-alert" data-apply-alert-notice-value="<%= notice %>">
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex justify-content-center align-items-center">
  <div class="text-dark-grey footer-copyright">
    © Helpderly  2022 - Tous droits réservés
  </div>
</div>

app/views/shared/_nav_pills.html.erb
<ul class="nav nav-pills nav-justified", style="width: 100%">
  <li class="nav-item mx-1">
    <a class="nav-link" aria-current="page" href="#">...waiting for validation</a>
  </li>
  <li class="nav-item mx-1">
    <a class="nav-link" href="#">Missions confirmed</a>
  </li>
  <li class="nav-item mx-1">
    <a class="nav-link" href="#">Missions done</a>
  </li>
</ul>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo-v3.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item me-3">
            <button type="button" style="background-color:white; border:none;" class="nav-link text-uppercase text-dark-grey animate-link" data-bs-toggle="modal" data-bs-target="#new_mission_modal" style="color: black;">
              Publish a mission <i class="fa fa-arrow-right"></i>
            </button>
          </li>
          <li class="nav-item me-3">
            <%= link_to missions_path, class: "nav-link text-uppercase text-dark-grey animate-link" do %>
              Find a mission <i class="fa fa-arrow-right"></i>
            <% end %>
          </li>
          <li class="nav-item">
            <%# juste pour avoir un visuel du user sur lequel on est connecté pendant le developpement%>
            <p class="nav-link text-dark-grey"><%= current_user.first_name %></p>
          </li>
          <li class="nav-item dropdown">
             <% if current_user.photo.key.nil? %>
                <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?b=1&s=170667a&w=0&k=20&c=eYsURDWBMsbvhjRxVQ8-pgC0q4b04DSYbCMnY5OlH14=" />
              <% else %>
                <div class="avatar dropdown-toggle cursor" id="navbarDropdown" aria-hashpopup="true" aria-expanded="false" data-bs-toggle="dropdown">
                  <%= cl_image_tag current_user.photo.key  %>
                </div>
              <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", dashboard_path, class: "dropdown-item text-dark-grey border-bottom p-2" %>
              <%= link_to "See my missions", mymissions_path, class: "dropdown-item text-dark-grey border-bottom p-2" %>
              <%= link_to "See my applications", mymissions_candidates_path, class: "dropdown-item text-dark-grey border-bottom p-2" %>
              <% if @messages > 0 %>
                <%= link_to chatrooms_path, class: "dropdown-item text-dark-grey border-bottom p-2", style:"display: flex; align-items: center; gap: 30px" do %>
                  Messages <span class="notif"><%= @messages %></span>
                <% end %>
              <% else %>
                <%= link_to "Messages", chatrooms_path, class:"dropdown-item text-dark-grey border-bottom p-2" %>
              <% end %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item text-dark-grey p-2" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item me-3">
            <%= link_to missions_path, class: "nav-link text-dark-grey text-uppercase animate-link" do %>
              Find a mission <i class="fa fa-arrow-right"></i>
            <% end %>
          </li>
          <li class="nav-item me-3">
            <%= link_to "Register", new_user_registration_path, class: "nav-link text-uppercase btn-animate" %>
          </li>
          <li class="nav-item me-3">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-uppercase btn-animate btn-outline " %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<%= render 'missions/mission_modal' unless controller_name == "missions" && action_name == "new" %>

app/views/shared/_navbar_dashboard.html.erb
<aside class="nav-dashboard float" style="width: 280px">
  <div class = "d-flex px-3 justify-content-center align-items-center">
    <div class="current-user d-flex" style="width: 100%">
      <% if current_user.photo.key.nil? %>
        <img class="avatar-large p-1 flex-shrink-0 align-items-center justify-content-center" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?b=1&s=170667a&w=0&k=20&c=eYsURDWBMsbvhjRxVQ8-pgC0q4b04DSYbCMnY5OlH14=" />
      <% else %>
        <div class="avatar-large p-1 flex-shrink-0 align-items-center justify-content-center" id="navbarDropdown" aria-hashpopup="true" aria-expanded="false" data-bs-toggle="dropdown">
          <%= cl_image_tag current_user.photo.key  %>
        </div>
      <% end %>
      <%= render '/missions/user_rating', instance: current_user %>
    </div>
  </div>
  <div class="d-flex flex-column flex-shrink-0 px-3">
    <ul class="nav flex-column mb-auto">
      <li class="nav-item mb-1">
        <a class="dashnav-link <%= "active" if action_name == "dashboard" %>" href="/dashboard">
          <i class="fa-solid fa-user"></i>
          Profil
        </a>
      </li>
      <li class="nav-item mb-1">
          <a class="dashnav-link <%= "active" if action_name == "myindex" %>" href="/mymissions">
            <i class="fa-solid fa-list"></i>
            My missions
          </a>
      </li>
      <li class="nav-item mb-1">
          <a class="dashnav-link <%= "active" if action_name == "myindex_candidate" %>" href="/mymissions_candidates">
            <i class="fa-solid fa-list"></i>
            My applications
          </a>
      </li>
      <li class="nav-item mb-1">
        <a class="dashnav-link <%= "active" if action_name == "index" %>" href="/chatrooms">
          <i class="fa-solid fa-message"></i>
          Messages
        </a>
      </li>

    </ul>
  </div>
</aside>

app/views/shared/_user_edit.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="col-12 d-flex">
      <div class="col-6 d-block p-2">
          <%= f.input :first_name,
                      autofocus: true,
                      input_html: { autocomplete: "first_name" }%>
      </div>
      <div class="col-6 d-block p-2">
          <%= f.input :last_name,
                      class: "col-10",
                      input_html: { autocomplete: "last_name" }%>
      </div>
    </div>
    <div class="col-12 d-flex">
      <div class="col-6 d-block p-2">
        <%= f.input :email,
                    input_html: { autocomplete: "email" }%>
      </div>
      <div class="col-6 d-block p-2">
        <%= f.input :phone_number,
                    input_html: { autocomplete: "phone_number" }%>
      </div>
    </div>
    <div class="col-12 d-block p-2">
        <%= f.input :description,
                    input_html: { :rows => 8, autocomplete: "description" } %>
    </div>
    <div class="col-12 d-block p-2">
      <%= f.input :photo, label:"Profil picture", as: :file, input_html: { multiple: false } %>
    </div>

    <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
          <p>En attente de confirmation pour: <%= resource.unconfirmed_email %></p>
    <% end %>
    <strong><p class="p-2">Change my password :</p></strong>
    <div class="col-12 d-flex">
      <div class="col-6 d-block p-2">
        <%= f.input :password,
                    label: "New password",
                    hint: "leave it blank if you don't want to change it",
                    required: false,
                    input_html: { autocomplete: "new-password" } %>
      </div>
      <div class="col-6 d-block p-2">
      <%= f.input :password_confirmation,
                  label: "New password confirmation",
                  required: false,
                  input_html: { autocomplete: "new-password" } %>
      </div>
    </div>
    <div class="col-12 d-flex">
      <div class="col-6 d-block p-2">
        <%= f.input :current_password,
                    hint: "we need your current password to confirm your new password",
                    required: true,
                    input_html: { autocomplete: "current-password" } %>
      </div>
    </div>
  </div>
  <div class="form-actions p-2">
    <%= f.button :submit, :class => "btn-orange p-2", placeholder: "Update" %>
  </div>
  <div class="col-12 d-block align-items-around p-2">
    <div><%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-light" %></div>
  </div>
<% end %>