config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  # routes pour reviews dans page user
  resources :users, only: [] do
    resources :reviews, only: %i[new create]
  end

  root to: "pages#home"
  get "dashboard", to: "pages#dashboard"
  get "mymissions", to: "missions#myindex"
  get "mymissions_candidates", to: "missions#myindex_candidate"
  get "user/:id", to: "pages#user", as: :userpage

  resources :missions do
    resources :mission_candidates, only: %i[create update edit destroy]
  end
  resources :chatrooms, only: %i[create show index] do
    resources :messages, only: :create
  end
  # routes pour décliner et accepter candidats à la mission
  resources :mission_candidates, only: [] do
    member do
      patch :accepted
      patch :declined
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/mission.rb
class Mission < ApplicationRecord
  include PgSearch::Model

  belongs_to :user
  has_many :mission_candidates, dependent: :destroy

  has_rich_text :content
  validates :title, presence: true
  validates :description, presence: true, length: { minimum: 10 }
  validates :reward_cents, presence: true, numericality: true
  validates :location, presence: true

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  acts_as_taggable_on :categories

  pg_search_scope :search_by_title_and_location,
                  against: %i[title location],
                  using: {
                    tsearch: { prefix: true }
                  }

  CATEGORIES = %w[shopping walking medical reading playing discussing]
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: %i[show edit update destroy]

  def index
    @missions = policy_scope(Mission).order(:start_date)
    @missions = @missions.tagged_with(params[:querychecks], any: true) if params[:querychecks].present?
    @missions = @missions.search_by_title_and_location(params[:querysearch]) if params[:querysearch].present?
    if params[:querydates].present? && params[:querydates].length == 1
      @missions = @missions.where("start_date >= ?", params[:querydates].first)
    elsif params[:querydates].present? && params[:querydates]
      dates = params[:querydates].map { |d| d.to_datetime.strftime("%B %d, %Y") }
      @missions = @missions.select do |mission|
        dates.include?(mission.start_date.strftime("%B %d, %Y")) unless mission.start_date.nil?
      end
    end

    respond_to do |format|
      format.html
      format.text { render partial: "missions/list", locals: { missions: @missions }, formats: [:html] }
    end
  end

  def myindex
    @mymissions = Mission.where("user_id = ?", current_user.id)
    authorize @mymissions
    respond_to do |format|
      format.html
      format.text { render partial: "missions/missions_recap", locals: { missions: @mymissions }, formats: [:html] }
    end
  end

  def myindex_candidate
    @mymissions_candidates = current_user.mission_candidates
    authorize @mymissions_candidates
    @my_missions_candidates = @mymissions_candidates.map(&:mission)
    respond_to do |format|
      format.html
      format.text { render partial: "missions/list", locals: { missions: @mymissions_candidates }, formats: [:html] }
    end
  end

  def show
    @chatroom = Chatroom.new
    authorize @mission
    @mission_candidate = MissionCandidate.new(mission: @mission)
    @mission_candidates = MissionCandidate.where(mission: @mission)
    @accepted_candidate = @mission.mission_candidates.accepted.first if @mission.status == true
    @waiting_candidates = @mission.mission_candidates.waiting if policy(@mission).destroy?
    @markers =
      [{
        lat: @mission.latitude,
        lng: @mission.longitude
      }]
  end

  def new
    @mission = Mission.new
    authorize @mission
  end

  def create
    @mission = Mission.new(mission_params)
    @mission.user = current_user
    @mission.reward_cents *= 100 if @mission.reward_cents
    @mission.category_list = params[:mission][:categories]
    authorize @mission
    if @mission.save
      redirect_to mymissions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @mission.reward_cents = @mission.reward_cents/100
    authorize @mission
  end

  def update
    authorize @mission
    if @mission.update(mission_params)
      redirect_to dashboard_path
    else
      render :edit, status: unprocessable_entity
    end
  end

  def destroy
    authorize @mission
    @mission.destroy
    redirect_to dashboard_path
  end

  private

  def set_mission
    @mission = Mission.find(params[:id])
  end

  def mission_params
    params.require(:mission).permit(:title, :description, :reward_cents, :location, :start_date, :categories)
  end
end

app/views/missions/_candidate_rating.html.erb
<p class="yellow-stars">
 <% unless instance.reviews.empty? %>
    <i class="fa-solid fa-star"></i>
    <%= instance.average_rating.round(1) %>
  <% end %>
</p>

app/views/missions/_candidates.html.erb
<figure class="avatar-large">
  <% if mission_candidate.user.photo.key.nil? %>
    <img src="https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?b=1&s=170667a&w=0&k=20&c=eYsURDWBMsbvhjRxVQ8-pgC0q4b04DSYbCMnY5OlH14=" />
  <% else %>
      <%= cl_image_tag mission_candidate.user.photo.key  %>
  <% end %>
</figure>
<div class="candidate-details d-flex flex-column justify-content-around">
  <div class="d-flex align-items-baseline gap-2">
    <h4><%= mission_candidate.user.fullname %></h4>
    <%= link_to 'details', userpage_path(mission_candidate.user) %>
  </div>
  <p>member since <%= mission_candidate.user.created_at.strftime('%B %Y') %> </p>
  <%# partial %>
  <%= render 'user_rating', instance: mission_candidate %>
</div>

app/views/missions/_checkboxes.html.erb
<div class="d-flex flex-column align-items-center p-2">
 <div>
    <i class="<%= find_icon(item) %>"></i>
 </div>
  <%= item %>
</div>

app/views/missions/_list.html.erb
<div data-search-missions-target="list">
  <% if missions.empty?  %>
    <p>There is no available missions currently</p>
  <% else %>
    <% missions.each do |mission| %>
    <%# faire un array avec toutes les current_user.mission_candidates.map(&:mission_id).includes?(mission.id) %>
      <% unless mission.start_date <= Time.now || current_user.mission_candidates.map(&:mission_id).include?(mission.id)%>
        <%= link_to mission_path(mission), class: "text-decoration-none" do %>
          <div class="row justify-content-center mb-5"  id="index-missions">
            <div class="col-md-12 col-xl-12">
              <div class="card shadow-0 cards-missions my">
                <div class="card-body ">
                  <div class="row">
                    <div class="col-md-6 col-lg-6 col-xl-6">
                      <div class="bg-image hover-zoom ripple rounded ripple-surface">
                        <figure class="d-flex text-truncate justify-content-beetwen align-items-center  m-auto" >
                          <h4 style="width: 100%"><strong><%= mission.title %></strong></h4>
                          <%if mission.category_list.first.nil? %>
                            <i class="fa-solid fa-sliders fs-4"></i>
                          <% else %>
                            <i class="<%= find_icon(mission.category_list.first)%> fs-4"></i>
                          <% end %>
                        </figure>
                      </div>
                      <div class="mt-1 mb-0 text-muted small">
                        <p><strong><i class="fa-regular fa-map"></i></strong> <%= mission.location %></p>
                      </div>
                      <div class="mt-1 mb-0 text-muted small">
                        <% unless mission.start_date.nil? %>
                          <p><strong><i class="fa-regular fa-clock"></i></strong>  <%= mission.start_date.strftime('%a %d %B %Y')%> at <%= mission.start_date.strftime('%I:%M%p')%></p>
                        <% end %>
                      </div>
                      <h6><strong>Mission description:</strong></h6>
                      <p class="text-truncate mb-4 mb-md-0">
                        <%= mission.description %>
                      </p>
                    </div>
                    <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start m-auto">
                      <div class="mt-1 mb-4">
                        <h6><strong>Status</strong></h6>
                        <% if (mission.status == true) && ((mission.start_date < Date.today) unless mission.start_date.nil?) %>
                          <h6 class="text-success">Mission done</h6>
                        <% elsif (mission.status == true) && ((mission.start_date > Date.today) unless mission.start_date.nil?) %>
                          <h6 class="text-alert"><i class="fa-sharp fa-solid fa-check"></i>  Mission confirmed</h6>
                        <% else %>
                          <h6 class="text-warning"><i class="fa-solid fa-users pe-2"></i> waiting for appliance</h6>
                        <% end %>
                      </div>
                      <div class="mt-1 mb-0">
                          <h6><strong>Reward</strong></h6>
                          <h6><strong><i class="fa-solid fa-money-bill"></i></strong>  <%= mission.reward_cents/100%> €</h6>
                      </div>
                    </div>
                    <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0 border-sm-start-none border-start d-flex align-items-center" style="padding: 7px 0">
                      <div class="d-flex d-column px-2 mb-2 flex-grow">
                        <figure class="avatar-circle-user m-1 ">
                          <% if mission.user.photo.key.nil? %>
                            <%= image_tag "default_avatar.png" %>
                          <% else %>
                              <%= cl_image_tag mission.user.photo.key %>
                          <% end %>
                        </figure>
                        <div class="flex-grow-1 py-2 px-3">
                          <h6><strong><%= mission.user.fullname %></strong></h6>
                          <%= render '/missions/candidate_rating', instance: mission.user %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/missions/_missions_candidate_recap.html.erb
<% @my_missions_candidates.each do |mission| %>
  <%= link_to mission_path(mission), class: "text-decoration-none" do %>
    <div class="row justify-content-center mb-5"  id="index-missions">
      <div class="col-md-12 col-xl-12">
        <div class="card shadow-0 cards-missions">
          <div class="card-body ">
            <div class="row">
              <div class="col-md-6 col-lg-6 col-xl-6 border-end border-sm-end-none">
                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                  <figure class="d-flex text-truncate justify-content-beetwen align-items-center  m-auto" >
                    <h4 style="width: 100%"><strong><%= mission.title %></strong></h4>
                    <%if mission.category_list.first.nil? %>
                      <i class="fa-solid fa-sliders fs-4"></i>
                    <% else %>
                      <i class="<%= find_icon(mission.category_list.first)%> fs-4"></i>
                    <% end %>
                  </figure>
                </div>
                <div class="mt-1 mb-0 text-muted small">
                  <p><strong><i class="fa-regular fa-map"></i></strong> <%= mission.location %></p>
                </div>
                <div class="mt-1 mb-3 text-muted small">
                  <% unless mission.start_date.nil? %>
                    <p><strong><i class="fa-regular fa-clock"></i></strong>  <%= mission.start_date.strftime('%a %d %B %Y')%> at <%= mission.start_date.strftime('%I:%M%p')%></p>
                  <% end %>
                </div>
                <h6 class="p"><strong>Mission description:</strong></h6>
                <p class="text-truncate mb-4 mb-md-0">
                  <%= mission.description %>
                </p>
              </div>
              <div class="col-md-6 col-lg-3 col-xl-3">
                <div class="mt-1 mb-4">
                  <h6><strong>Status</strong></h6>
                  <% if (mission.status == true) && ((mission.start_date < Date.today) unless mission.start_date.nil?) %>
                      <h6 class="text-success">Mission done</h6>
                    <% elsif (mission.status == true) && ((mission.start_date > Date.today) unless mission.start_date.nil?) %>
                      <h6 class="text-alert"><i class="fa-sharp fa-solid fa-check"></i>  Mission confirmed</h6>
                    <% else %>
                      <h6 class="text-warning text-right"><i class="fa-regular fa-clock"></i>...waiting for approval</h6>
                  <% end %>
                </div>
                <div class="mt-1 mb-0">
                    <h6><strong>Reward</strong></h6>
                    <h6><strong><i class="fa-solid fa-money-bill"></i></strong>  <%= mission.reward_cents/100%> €</h6>
                </div>
              </div>
              <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0 border-sm-start-none border-start d-flex align-items-center" style="padding: 7px 0">
                <div class="d-flex d-column px-2 mb-2 flex-grow">
                  <figure class="avatar-circle-user m-1 ">
                    <% if mission.user.photo.key.nil? %>
                      <%= image_tag "default_avatar.png" %>
                    <% else %>
                        <%= cl_image_tag mission.user.photo.key %>
                    <% end %>
                  </figure>
                  <div class="flex-grow-1 py-2 px-3">
                    <h6><strong><%= mission.user.fullname %></strong></h6>
                    <%= render '/missions/candidate_rating', instance: mission.user %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/missions/_missions_recap.html.erb
<% @mymissions.each do |mission| %>
  <%= link_to mission_path(mission), class: "text-decoration-none" do %>
    <div class="row justify-content-center mb-5"  id="index-missions">
      <div class="col-md-12 col-xl-12">
        <div class="card shadow-0 cards-missions">
          <div class="card-body ">
            <div class="row">
              <div class="col-md-6 col-lg-6 col-xl-6 border-end border-sm-end-none">
                <div class="bg-image hover-zoom ripple rounded ripple-surface">
                  <figure class="d-flex text-truncate justify-content-beetwen align-items-center  m-auto" >
                    <h4 style="width: 100%"><strong><%= mission.title %></strong></h4>
                    <%if mission.category_list.first.nil? %>
                      <i class="fa-solid fa-sliders fs-4"></i>
                    <% else %>
                      <i class="<%= find_icon(mission.category_list.first)%> fs-4"></i>
                    <% end %>
                  </figure>
                </div>
                <div class="mt-1 mb-0 text-muted small">
                  <p><strong><i class="fa-regular fa-map"></i></strong> <%= mission.location %></p>
                </div>
                <div class="mt-1 mb-3 text-muted small">
                  <% unless mission.start_date.nil? %>
                    <p><strong><i class="fa-regular fa-clock"></i></strong>  <%= mission.start_date.strftime('%a %d %B %Y')%> at <%= mission.start_date.strftime('%I:%M%p')%></p>
                  <% end %>
                </div>
                <h6 class="p"><strong>Mission description:</strong></h6>
                <p class="text-truncate mb-4 mb-md-0">
                  <%= mission.description %>
                </p>
              </div>
              <div class="col-md-6 col-lg-3 col-xl-3">
                <div class="mt-1 mb-4">
                  <h6><strong>Status</strong></h6>
                  <% if (mission.status == true) && ((mission.start_date < Date.today) unless mission.start_date.nil?) %>
                      <h6 class="text-success">Mission done</h6>
                    <% elsif (mission.status == true) && ((mission.start_date > Date.today) unless mission.start_date.nil?) %>
                      <h6 class="text-alert"><i class="fa-sharp fa-solid fa-check"></i>  Mission confirmed</h6>
                    <% else %>
                      <h6 class="text-warning text-right"><i class="fa-regular fa-clock"></i>...waiting for approval</h6>
                  <% end %>
                </div>
                <div class="mt-1 mb-0">
                    <h6><strong>Reward</strong></h6>
                    <h6><strong><i class="fa-solid fa-money-bill"></i></strong>  <%= mission.reward_cents/100%> €</h6>
                </div>
              </div>
              <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0 border-sm-start-none border-start" style="padding: 7px 0">
                <h6 class="px-2"><strong>Candidates (<%= mission.mission_candidates.count %>)</strong></h6>
                <div class="d-flex flex-column vertical-scroll" style="height: 130px">
                  <% if mission.status == true %>
                    <% mission.mission_candidates.where(mission_id:mission.id).order(:status).each do |candidate| %>
                      <div class="d-flex d-column shadow-sm position-relative px-2 mb-2">
                        <figure class="avatar-circle-user m-1 <%= candidate.status == "Declined" ? "trash-candidate" : "bg-white" %>">
                          <% if candidate.user.photo.key.nil? %>
                           <%= image_tag "default_avatar.png" %>
                          <% else %>
                              <%= cl_image_tag candidate.user.photo.key %>
                          <% end %>
                        </figure>
                        <div class="flex-grow-1 py-2 px-3">
                          <h6><strong><%= candidate.user.fullname %></strong></h6>
                          <%= render '/missions/candidate_rating', instance: candidate.user %>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <% mission.mission_candidates.where(mission_id: mission.id, user_id: current_user.id).each do |candidate| %>
                      <div class="d-flex d-column shadow-sm position-relative px-2 mb-2 ">
                        <figure class="avatar-circle-user m-1 <%= candidate.status == "Declined" ? "trash-candidate" : "bg-white" %>">
                          <% if candidate.user.photo.key.nil? %>
                           <%= image_tag "default_avatar.png" %>
                          <% else %>
                              <%= cl_image_tag candidate.user.photo.key %>
                          <% end %>
                        </figure>
                        <div class="flex-grow-1 py-2 px-3">
                          <h6><strong><%= candidate.user.fullname %></strong></h6>
                          <%= render '/missions/candidate_rating', instance: candidate.user %>
                        </div>
                      </div>
                    <% end %>
                    <% mission.mission_candidates.where(mission_id: mission.id).where.not(user_id: current_user.id).each do |candidate| %>
                      <div class="d-flex d-column shadow-sm position-relative px-2 mb-2">
                        <figure class="avatar-circle-user m-1 <%= candidate.status == "Declined" ? "trash-candidate" : "bg-white" %>">
                          <% if candidate.user.photo.key.nil? %>
                           <%= image_tag "default_avatar.png" %>
                          <% else %>
                              <%= cl_image_tag candidate.user.photo.key %>
                          <% end %>
                        </figure>
                        <div class="flex-grow-1 py-2 px-3">
                          <h6><strong><%= candidate.user.fullname %></strong></h6>
                          <%= render '/missions/candidate_rating', instance: candidate.user %>
                        </div>
                      </div>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/missions/index.html.erb
<div data-controller="search-missions">
  <div id="banner-search">
    <div class="container">
      <h1 class="text-center mb-4">Search a mission</h1>
      <div class="row justify-content-center">
        <%= form_with(url: missions_path, method: :get, html: {class:
          "mb-4 col-10 px-0", data: {search_missions_target: "form"}}) do |f| %>
          <div class="row">
          <div class="col-8">
            <%= f.text_field :querysearch,
                            class: "form-control",
                            placeholder: "Type a mission title",
                            value: params[:querysearch],
                            data: {
                              search_missions_target: "input",
                              action: "keyup->search-missions#update"
                            } %>
          </div>
          <div class="col-4">
            <%= f.date_field :start_date, placeholder:"Pick a Date",
              as: :string,
              class: 'form-control',
              data: {
                search_missions_target: "date",
                action: "change->search-missions#update"
              }
            %>
          </div>
          </div>
          <div class="d-flex mt-4 justify-content-between fs-5">
            <% Mission::CATEGORIES.each_with_index do |category, index| %>
              <div class="checkbox-inputs">
                <%= f.check_box category, class: "d-none", data: {
                  search_missions_target: "checkbox",
                  action: "change->search-missions#update"
                } %>
                <div class="d-flex flex-column align-items-center p-2" data-search-missions-target="label">
                  <%= f.label category do%>
                    <i class="<%= find_icon(category) %>"></i>
                  <% end %>
                  <%= f.label category, category.to_s %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="container" id="index-missions">
    <div class="row justify-content-center pt-4">
      <div class="col-10">
        <%= render "list", missions: @missions %>
      </div>
    </div>
  </div>
</div>

app/views/missions/show.html.erb
<div class="py-5">
  <div class="container">
    <% if @mission.user == current_user %>
      <%= link_to(mymissions_path, class:"btn btn-orange") do  %>
        <i class="fa-solid fa-arrow-left-long"></i>
      <% end %>
    <% else %>
      <%= link_to(missions_path, class:"btn btn-orange") do  %>
        <i class="fa-solid fa-arrow-left-long"></i>
      <% end %>
    <% end %>
    <div class="row mt-4">
      <%# quand le user est celui qui a posté la mission %>
      <% if policy(@mission).edit? %>
        <div class="left-col col-7 pe-5">
          <h3>Candidates</h3>
          <div class="mission-candidates border-description">
            <%# quand un user est validé %>
            <% if @mission.status == true %>
              <% @mission.mission_candidates.where(mission_id: @mission.id).order(:status).each do |candidate| %>
                <div class="card-container d-flex gap-4 border p-3 <%= candidate.status == "Declined" ? "trash-candidate pe-none" : "bg-white" %>">
                  <%# partial %>
                  <%= render 'candidates', mission_candidate: candidate %>
                </div>
              <% end %>

            <%#  %>
            <%# quand aucun user n'a été validé %>
            <% elsif @mission.status == false %>
              <% @waiting_candidates.where(mission_id: @mission.id).each do |candidate| %>
                <div class="card-container d-flex justify-content-between p-3 bg-white">
                  <%# partial %>
                  <%= render 'candidates', mission_candidate: candidate %>
                  <div class="action-button d-flex flex-column justify-content-around align-items-center pe-4">
                    <p><%= link_to "Accept", accepted_mission_candidate_path(candidate), data: {turbo_method: :patch}, class: "btn btn-orange" %></p>
                    <p><%= link_to "Decline", declined_mission_candidate_path(candidate), data: {turbo_method: :patch}, class:"text-decoration-none" %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          <%#  %>
          </div>
        </div>

        <div class="right-col col-5">
        <h3>Description</h3>
          <div class="px-4 py-2 bg-white card-container">
            <div class="d-flex align-items-center gap-3">
              <h1 class="pt-2"><%= @mission.title.capitalize %></h1>
            <%# peut retiré la condition ? %>
              <% unless policy(@mission_candidate).new? %>
                <div class="ms-auto d-flex gap-3">
                  <%= link_to edit_mission_path(@mission), class:"btn btn-orange" do %>
                    <i class="fas fa-edit"></i>
                  <% end %>
                  <%= button_to @mission, method: :delete do %>
                    <i class="far fa-trash-alt"></i>
                  <% end %>
                </div>
              <% end %>
            </div>
            <div class="d-flex align-items-center img-wrapper">
              <figure class="avatar-circle-user">
                <% if @mission.user.photo.key.nil? %>
                  <img src="https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?b=1&s=170667a&w=0&k=20&c=eYsURDWBMsbvhjRxVQ8-pgC0q4b04DSYbCMnY5OlH14=" />
                <% else %>
                    <%= cl_image_tag @mission.user.photo.key  %>
                <% end %>
              </figure>
              <p class="m-2">
                Posted by <%= link_to @mission.user.first_name.capitalize, userpage_path(@mission.user) %>
              </p>
            </div>
            <p class="mt-2"><%= @mission.description %></p>
            <div class="icons-div">
              <% unless @mission.start_date.nil? %>
                <p><strong><i class="fa-regular fa-clock"></i></strong>  <%= @mission.start_date.strftime('%a %d %B %Y')%></p>
              <% end %>
              <p><strong><i class="fa-regular fa-map"></i></strong> <%= @mission.location %></p>
              <p><strong><i class="fa-regular fa-money-bill-1"></i> <%= @mission.reward_cents/100 %></strong> €</p>
            <%# peut être retiré ? %>
              <% if policy(@mission_candidate).new? %>
                <% if @mission.mission_candidates.none? {|candidate| candidate.user == current_user} %>
                  <%= link_to "Apply to this mission", mission_mission_candidates_path(@mission), data: { turbo_method: :post }, class: "btn btn-orange" %>
                <% end %>
              <% end %>
            <%#  %>
            </div>
          </div>
          <div style="width: 100%; height: 300px;"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>


    <%# quand user n'est pas le poster de la mission %>
      <% else %>
        <div class="left-col col-7 pe-5">
          <h3>Description</h3>
          <div class="p-4 bg-white border-description">
            <div class="d-flex align-items-center gap-3">
              <h1 class="pt-2"><%= @mission.title.capitalize %></h1>
            </div>
            <div class="d-flex align-items-center img-wrapper">
              <figure class="avatar-circle-user">
                <% if @mission.user.photo.key.nil? %>
                  <img src="https://media.istockphoto.com/id/1337144146/fr/vectoriel/vecteur-dic%C3%B4ne-de-profil-davatar-par-d%C3%A9faut.jpg?b=1&s=170667a&w=0&k=20&c=eYsURDWBMsbvhjRxVQ8-pgC0q4b04DSYbCMnY5OlH14=" />
                <% else %>
                    <%= cl_image_tag @mission.user.photo.key  %>
                <% end %>
              </figure>
              <p>
                Posted by <%= link_to @mission.user.first_name.capitalize, userpage_path(@mission.user) %>
              </p>
            </div>
            <p><%= @mission.description %></p>
            <% unless @mission.start_date.nil? %>
              <p><i class="fa-regular fa-clock"></i>  <%= @mission.start_date.strftime('%a %d %B %Y')%></p>
            <% end %>
            <p><i class="fa-regular fa-map"></i> <%= @mission.location %></p>
            <p><i class="fa-regular fa-money-bill-1"></i> <strong><%= @mission.reward_cents/100 %></strong> €</p>
          <%# si user n'a pas encore postulé %>
            <% if policy(@mission_candidate).new? %>
              <% if @mission.mission_candidates.none? {|candidate| candidate.user == current_user} %>
                <%= link_to "Apply to this mission", mission_mission_candidates_path(@mission), data: { turbo_method: :post }, class: "btn btn-orange" %>
              <% end %>
            <% end %>
          <%#  %>
          </div>
          <div style="width: 100%; height: 300px;"
                data-controller="map"
                data-map-markers-value="<%= @markers.to_json %>"
                data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>
        </div>
        <div class="right-col col-5">
          <h3>Candidates</h3>
          <div class="mission-candidates">
            <% if @mission.status == true %>
              <% @mission.mission_candidates.where(mission_id: @mission.id).order(:status).each do |candidate| %>
                <div class="card-container d-flex gap-4 border p-3 <%= candidate.status == "Declined" ? "trash-candidate pe-none" : "bg-white" %>">
                  <%# partial %>
                  <%= render 'candidates', mission_candidate: candidate %>
                </div>
              <% end %>
            <% else %>
              <% if @mission.mission_candidates.where(mission_id: @mission.id).empty? %>
                <p>Be the first to apply for this mission.</p>
              <% else %>
                <% @mission.mission_candidates.where(mission_id: @mission.id, user_id: current_user.id).each do |candidate| %>
                  <div class="card-container d-flex gap-4 border p-3 bg-white">
                    <%# partial %>
                    <%= render 'candidates', mission_candidate: candidate %>
                  </div>
                <% end %>
                <% @mission.mission_candidates.where(mission_id: @mission.id).where.not(user_id: current_user.id).each do |candidate| %>
                  <div class="card-container pe-none d-flex gap-4 border p-3 trash-candidate">
                    <%# partial %>
                    <%= render 'candidates', mission_candidate: candidate %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>